Note that supertrait StrategyReporter is not used because of error[E0658]: associated type defaults are unstable This means we will fall back to some redundancy one level lower: PermutateReporter, EvolveReporter, HillClimbReporter